### PR TITLE
Renamed all tags from wts.* to ts.*

### PR DESCRIPTION
**Pull request by mikebattista**
# PR checklist

**Quick summary of changes**
Definitive list of all tags was in `code\test\SharedFunctionality.Tests\TemplateValidator\TemplateJsonVerifier.cs`. Used global search and replace to rename each individual tag and updated the `TagPrefix` variable [here](https://github.com/microsoft/TemplateStudio/blob/542b8c20bfdc63c0e96b68706351c588f97b10f1/code/SharedFunctionality.Core/Templates/ITemplateInfoExtensions.cs#L21) to "ts.". The tag names are mainly used as key names and in string comparisons like in `code\SharedFunctionality.Core\Templates\ITemplateInfoExtensions.cs`. Updated all references I could find.

**Which issue does this PR relate to?**
#4396

**Applies to the following platforms:**

- [ ] WinUI
- [ ] WPF
- [ ] UWP

**Anything that requires particular review or attention?**

**Do all automated tests pass?**

**Have automated tests been added for new features?**

**If you've changed the UI:**
  - Be sure you are including screenshots to show the changes.
  - Be sure you have reviewed the [accessibility checklist](accessibility.md).

**If you've included a new template:**
  - Be sure you reviewed the [Template Verification Checklist](https://github.com/microsoft/TemplateStudio/wiki/Checklist:-Template-Verification).
  - Be sure it's included in the list on this [UWP](https://github.com/microsoft/TemplateStudio/blob/main/docs/UWP/getting-started-endusers.md) or [WPF](https://github.com/microsoft/TemplateStudio/blob/main/docs/WPF/getting-started-endusers.md) getting started doc.

**Have you raised issues for any needed follow-on work?**

**Have docs been updated?**

**If breaking changes or different ways of doing things have been introduced, have they been communicated widely?**

### CODE REVIEW

**Comment by mrlacey** [comment]
There is a lot more still to be done here:

Find "wts." Matching lines = 1894


And that doesn't even include the file renames.

**Comment by mikebattista** [comment]
The scope of this PR is tags.

**Comment by mrlacey** [comment]
> The scope of this PR is tags.

There's code that assumes the same prefix for everything. Even in tests. That's probably why tests are failing.

**Comment by mikebattista** [comment]
Yes I fixed one test with https://github.com/microsoft/TemplateStudio/pull/4446/commits/7f08f06ae8f94fe521b09fda8d2257e267ef10e0.

Looking at the other failed test now.

**Comment by mrlacey** [comment]
> The scope of this PR is tags.

There is code that assumes the same prefix for all tags. Even in tests. That's probably why some tests are failing.

**Comment by mikebattista** [comment]
CI tests are passing now.

**Review by mrlacey — APPROVED** [review]

**Pull request merged**
