### PR TITLE
Use expression body on properties and prefer compound assignment CA fixes

### PR DESCRIPTION
**Pull request by mikebattista**
# PR checklist

**Quick summary of changes**

**Which issue does this PR relate to?**
#4374

**Applies to the following platforms:**

- [x] WinUI
- [ ] WPF
- [ ] UWP

**Anything that requires particular review or attention?**

**Do all automated tests pass?**

**Have automated tests been added for new features?**

**If you've changed the UI:**
  - Be sure you are including screenshots to show the changes.
  - Be sure you have reviewed the [accessibility checklist](accessibility.md).

**If you've included a new template:**
  - Be sure you reviewed the [Template Verification Checklist](https://github.com/microsoft/TemplateStudio/wiki/Checklist:-Template-Verification).
  - Be sure it's included in the list on this [UWP](https://github.com/microsoft/TemplateStudio/blob/main/docs/UWP/getting-started-endusers.md) or [WPF](https://github.com/microsoft/TemplateStudio/blob/main/docs/WPF/getting-started-endusers.md) getting started doc.

**Have you raised issues for any needed follow-on work?**
#4486
#4487 

**Have docs been updated?**

**If breaking changes or different ways of doing things have been introduced, have they been communicated widely?**

### CODE REVIEW

**Comment by mrlacey** [comment]
This claims to fix #4374 but it leaves lots of the questions there unanswered.

Original questions:

- Should the generated code all use the same formatting for body blocks, or should expression bodies be used for properties where they can be?
- What about other places in the code where expression bodies, or other new/simplified syntax can be used?
- Where else, apart from the WebView pages, needs to be updated?


This PR only modifies the ViewModel files but there are other files in the generated code that have properties that use a different syntax that have not been updated. Is the intention to only modify the VMs and close the original issue? Why was this decision not documented?

What about other changes that can be made to the generated code to take advantage of other language improvements that are also prompted by the compiler? Such as pattern matching, expression simplification, and declaration inlining?

One of the factors that lead to the raising of the original issue was inconsistency in the generated code.
To address the possibility of future inconsistencies (and the support and rework they will bring), two things are needed:
1. Documentation of the expectations of generated code standards.
2. Tests that automatically verify the enforcement of such standards.

Without the above, submitting this PR now, and closing the associated issue will just lead to more (unnecessary?) work in the future.

**Comment by mikebattista** [comment]
The changes here are clearly better than before (improved local consistency within a given file and leverages latest language features). I'm not going to block on everything else you've listed to improve the templates.

Where else should these expression and ??= patterns be applied? I looked through a generated project with all pages and features and updated the patterns that were called out in #4374. If there are other cases, happy to add those to this PR.

Application of other language features should have separate issues. Also, what do I have to enable to get these compiler warnings for new language features? I don't see any warnings in generated projects.

**Comment by mrlacey** [comment]
I don't want to block this PR. What I don't want to do is approve this PR on the basis that it "fixes" the linked issue.
It does not cover everything mentioned in that issue and when an issue is "fixed" it is closed.

This is also a great example of why simply addressing the reported instances in an issue is often an insufficient response.
It's not enough to only address the reported problem. It's also necessary to ensure that other, related, instances are addressed and the circumstances that allowed the issue to surface are addressed so a similar thing can't happen again in the future.

Here the issue was that the generated code was inconsistent. Therefore, in addition to addressing the highlighted inconsistencies, a complete solution should also stop (or at least highlight) any future inconsistencies getting into the codebase.

If this had been done, it would have flagged the issues found in [a838f4c](https://github.com/microsoft/TemplateStudio/pull/4484/commits/a838f4c8b086477ed12effc7c506823cc84a639d)
It would also have found the properties [here](https://github.com/microsoft/TemplateStudio/blob/main/code/TemplateStudioForWinUICs/Templates/_comp/MT/Project.SplitView/Behaviors/NavigationViewHeaderBehavior.cs#L18) and [here](https://github.com/microsoft/TemplateStudio/blob/main/code/TemplateStudioForWinUICs/Templates/Pg/List/Param_ProjectName/Views/Param_ItemNameDetailControl.xaml.cs#L11) that are not using expression bodies for assignment.



If separate issues are to be raised to track related tasks or parts of the work not done at this time, then those issues should be created before a PR is raised.

I'm used to PRs being raised only when the work is finished.
If a PR is being raised on the basis that it only does part of the work in the linked issue I would expect that to be called out in the description accompanying the PR.

In this instance, the only information accompanying the PR is the number of the issue that it "fixes". When I go to that issue I see a number of unanswered questions. Not knowing the intended approach towards answering these questions, the best I can do to review the PR is to try any work out the intentions from the changes that have been made. This takes a lot more time and effort and as it relies on assumptions, my guesses could be wrong.

I am used to work being defined before being asked to review it. 
Across almost all open-source projects I know, there is the request that work is discussed in an issue before any changes are made. 

This [used to be in the contributing guide for this project](https://github.com/microsoft/TemplateStudio/commit/6dda0dc4d44a2ac3425f9273aa7098b3c8254a66) too.

> Please comment on an [issue](https://github.com/microsoft/TemplateStudio/issues) to let us know you're interested in working on something before you start the work. Not only does this avoid multiple people unexpectedly working on the same thing at the same time but **it enables us to make sure everyone is clear on what should be done to implement any new functionality. It's less work for everyone, in the long run, to establish this up front.**

(Emphasis added) I hadn't realized that this was removed.

The PR template also has questions that weren't answered.
If these questions don't need to be answered they should be removed from the template.

The actions of core contributors and project owners set an example for future contributors.
It would be easy to look at this issue/PR and assume:
- Filling in template questions is optional.
- It's ok to submit changes without discussing them first.
- Making a positive change is a justification for ignoring wider issues and the consequences of related future work.
- The amount of effort required by a reviewer isn't worth considering.


---


Of course, if all you want to do is make an incremental improvement in the templates you have the permissions to do that without requiring me to approve them.

**Comment by mikebattista** [comment]
The scope of the original issue was pretty clear and has been addressed by this PR. Original issue was specifically about WebView, but this PR expanded the fix to resolve other occurrences as well. I've also filed a separate issue (#4486) to fix other CA warnings now that I see those (needed to run CA and then also enable Messages in the Error List).

To answer your questions from the original issue:

* Expression syntax should be used wherever possible especially if CA is complaining about it
* Other occurrences in the code have been updated barring any I missed (CA pointed out the last couple that I missed at least for compound assignment)
* Other CA fixes are tracked by #4486 and we should fix all of them

Regarding testing, we could use some content in the contributor guide about the organization of tests and how to augment them. For contributors adding new templates, how much coverage of those is picked up by existing tests vs. needs new coverage? If you want to apply a pattern to all generated projects, what is the scaffolding for that test?

We should definitely have a test that validates there are no CA warnings out-of-the-box in the templates. I hadn't seen those warnings until I ran CA and turned on Messages in the Error List. Part of promoting leading practices in Template Studio is also promoting use of latest language features. We can add that test as part of #4486.

So this test would need to:

* Generate all combinations of projects
* Run CA on all of them
* Fail if reported issues are > 0

Do you have guidance for "how to apply a pattern to all generated projects"?

**Review by mrlacey — APPROVED** [review]

**Pull request merged**
