### PR TITLE
Add Single Instance Template

### LINKED ISSUE #4662: Add a Single-Instance option for WinUI 3
### Is your feature request related to a problem? Please describe.

WinUI apps are multi-instance by default, and it isn't straightforward to make an app single-instance.

### Describe the solution you'd like

If the TemplateStudio had a Single-Instance option for WinUI that would save us all some time and effort.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Applies to the following platforms:

- [X] WinUI
- [X] WPF
- [ ] UWP

### PR DESCRIPTION
**Pull request by Mysterious-Dev**
# PR checklist

**Quick summary of changes**

This PR add single instance template for `Template Studio for WinUI (C#)`.

I based my work on : https://blogs.windows.com/windowsdeveloper/2022/01/28/making-the-app-single-instanced-part-3/

**Which issue does this PR relate to?**

Close #4662 

**Applies to the following platforms:**

- [x] WinUI
- [ ] WPF
- [ ] UWP

### CODE REVIEW

**Comment by mrlacey** [comment]
Where's the implementation?
Do you really need all those symbols?

No icon or description files? - How does this show in the UI?


-Oh, just seen this is still in draft. Still consider the above though.

**Comment by Mysterious-Dev** [comment]
Yes, I'm working on it, I've opened the PR but I'm working on it bit by bit ^^

**Comment by Mysterious-Dev** [comment]
By the way, for the icon, I'm not very good at making them ^^.

**Comment by Mysterious-Dev** [comment]
@mikebattista, @pratikone, @bpulliam, well I think I finish the work (for the moment). For the icon, is it possible to ask someone with more experience to do it (I don't know who made the other icons)?

**Comment by humbertomoli99** [comment]
this exists in uwp, just have to move uwp settings to winui3?
image

**Comment by Mysterious-Dev** [comment]
Maybe not.

**Comment by Mysterious-Dev** [comment]
@pratikone @mikebattista Any news ?

**Pull request closed without merging**
