### PR TITLE
CHANGES

### PR DESCRIPTION
**Pull request by Kryslynn93**
# PR checklist

**Quick summary of changes**

**Which issue does this PR relate to?**

**Applies to the following platforms:**

- [ ] WinUI
- [ ] WPF
- [ ] UWP

**Anything that requires particular review or attention?**

**Do all automated tests pass?**

**Have automated tests been added for new features?**

**If you've changed the UI:**
  - Be sure you are including screenshots to show the changes.
  - Be sure you have reviewed the [accessibility checklist](accessibility.md).

**If you've included a new template:**
  - Be sure you reviewed the [Template Verification Checklist](https://github.com/microsoft/TemplateStudio/wiki/Checklist:-Template-Verification).
  - Be sure it's included in the list on this [UWP](https://github.com/microsoft/TemplateStudio/blob/main/docs/UWP/getting-started-endusers.md) or [WPF](https://github.com/microsoft/TemplateStudio/blob/main/docs/WPF/getting-started-endusers.md) getting started doc.

**Have you raised issues for any needed follow-on work?**

**Have docs been updated?**

**If breaking changes or different ways of doing things have been introduced, have they been communicated widely?**

### CODE REVIEW

**Review by Kryslynn93 — COMMENTED** [review]
APPROVED

**Comment by mrlacey** [comment]
@Kryslynn93 Can you explain why you're submitting this PR that looks like a very generic build script that has had no attempt at customization to work with the solution?
Also, as the project already has build scripts that run as part of the CI, why is this deemed necessary/appropriate?

**Comment by pratikone** [comment]
closing this as it looks like an attempt to trigger CI build on PR unauthorized.

**Comment by mrlacey** [comment]
> closing this as it looks like an fishy attempt to trigger CI build on PR unauthorized.

I assumed it was a (possibly [semi-]automated) way of someone getting hacktoberfest points by adding a file that is commonly used and often even suggested by GitHub as an addition.

**Comment by pratikone** [comment]
Oh. could be though I am more careful because there has been a security attack on other repo using same operation.

**Comment by mrlacey** [comment]
Because the file contained no configuration or variation from the default, I didn't even think of the security angle.
Although it did make me look to see if GitHub had a way of limiting PRs to certain code paths, but I couldn't find anything built-in.

**Pull request closed without merging**
