### PR TITLE
Updated WPF Templates

### PR DESCRIPTION
**Pull request by mikebattista**
# PR checklist

**Quick summary of changes**
Updated the WPF templates to .NET 6.

**Which issue does this PR relate to?**
https://github.com/microsoft/TemplateStudio/issues/4401

**Applies to the following platforms:**

| UWP              | WPF              | WinUI            |
| :--------------- | :--------------- | :----------------|
| No | Yes | No |

**Anything that requires particular review or attention?**

**Do all automated tests pass?**

**Have automated tests been added for new features?**

**If you've changed the UI:**
  - Be sure you are including screenshots to show the changes.
  - Be sure you have reviewed the [accessibility checklist](accessibility.md).

**If you've included a new template:**
  - Be sure you reviewed the [Template Verification Checklist](https://github.com/microsoft/WindowsTemplateStudio/wiki/Checklist:-Template-Verification).
  - Be sure it's included in the list on this [UWP](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/getting-started-endusers.md) or [WPF](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/WPF/getting-started-endusers.md) getting started doc.

**Have you raised issues for any needed follow-on work?**

**Have docs been updated?**

**If breaking changes or different ways of doing things have been introduced, have they been communicated widely?**

### CODE REVIEW

**Comment by mrlacey** [comment]
Are the failing CI tests because they are running on VS2022, when this is for the VS2019 version of the code?

There appears to be little more here than an update of references from the existing 3.1 templates. Is this all that was intended? I'd expect a new WPF project that uses .NET6 to take advantage of the changes and differences that the new version of dotnet brings.

**Comment by mikebattista** [comment]
> I'd expect a new WPF project that uses .NET6 to take advantage of the changes and differences that the new version of dotnet brings.

What specific changes would you like to see? First step is to update to target .NET 6 and support VS 2022, then we can add new features after you merge your refactor work.

**Comment by mrlacey** [comment]
@mikebattista  Do all tests run locally for you? I get some tests failing on my local machine when running in VS2019 & in VS2022. Which version(s) of VS are you using, and expecting this to work with?

**Comment by mikebattista** [comment]
We should be working in VS 2022 at this point. We can reevaluate the tests and CI pipelines after your refactor work is merged in.

**Comment by mikebattista** [comment]
Are you merging my template changes at the same time as the rest of the refactoring work? I'd first get things running without my changes.

**Comment by mrlacey** [comment]
> Are you merging my template changes at the same time as the rest of the refactoring work? I'd first get things running without my changes.

I was looking to see if they could merge in first.
I don't expect them to merge when I'm done. Or rather, they will but will then need to be moved/duplicated to their new place in the project structure.

**Comment by mikebattista** [comment]
Ok. I'm happy to merge my changes in myself once your refactoring work is integrated.

The CI pipelines do need to be updated to run on the windows-2022 images and update the versions of .NET used for example. It's possible the existing tests will need to be updated for VS 2022 as well. I haven't tried them locally. I just made the minimum changes required to get the CI pipelines running in my forks.

**Comment by mrlacey** [comment]
Can this be reverted to draft and just kept as a reference until the appropriate changes are made separately?
Due to the extensive structural changes that have been made (& merged) since was opened, attempting to update these changes and merge with the main branch is likely to be very difficult and fragile.

**Comment by mikebattista** [comment]
Replaced by #4422.

**Pull request closed without merging**
