### PR TITLE
Revert "Removes workaround theming code for WinUI 3 custom titlebar"  => solving title bar problem when changing theme

### PR DESCRIPTION
**Pull request by humbertomoli99**
Reverts microsoft/TemplateStudio#4621

### CODE REVIEW

**Comment by humbertomoli99** [comment]
I have no idea why it doesn't compile, I'm supposed to be merging the verified main branch, I don't understand (All checks have passed)

**Comment by RyanLua** [comment]
> @pratikone I would wait it for a while until I get to reproduce the bug. You said it is appearing in win10 or 11 ?

I have the same issue and was able to repo. I'm on Windows 11. Below is my windows specs.
```
Edition	Windows 11 Home
Version	22H2
Installed on	‎2/‎8/‎2023
OS build	22621.1555
Experience	Windows Feature Experience Pack 1000.22640.1000.0
```

Issue #4628 has more information about repo and such. I used the same repo steps as #4628.

**Comment by pratikone** [comment]
this looks good. It took me some time before I was deciding whether to do a small release for this or wait till winui 3 + appwindow titlebar merger is completed as these issues will be resolved by that. Now I have enough changes to do a small release, so this PR can be merged now. Thanks for the patience.

**Review by pratikone — APPROVED** [review]

**Comment by pratikone** [comment]
Thanks @humbertomoli99 . This is now merged into main. I will initiate a new smaller release soon.

**Pull request merged**
