### PR TITLE
Add MSTest support

### PR DESCRIPTION
**Pull request by smorin4**
# PR checklist

Added MSTests option to wizard. Generates MSTest project that references main/core projects and includes scaffolding + stubs for testing the view models used by different added pages. Currently supports MSIX packaged and unpackaged projects.

Issue: #4528 

**Applies to the following platforms:**

- [x] WinUI
- [ ] WPF
- [ ] UWP

**Anything that requires particular review or attention?**

Currently contains a bug with ResourceLoader, which is responsible for obtaining app settings data for the Settings View Model. The test project is unable to retrieve the resource file from the main project. Therefore, when all pages are added and their corresponding tests are run, all will pass except for the SettingViewModelTest.

Addition to wizard:
Testing Screenshot

### CODE REVIEW

**Comment by mikebattista** [comment]
With the edit project menu now restored, let's make sure the MSTest project is offered under the test menu.

**Comment by mikebattista** [comment]
@smorin4 the tests are discovered for me but don't run in the generated project. Could you take a look?

Also could you test with all the different architectures that the app supports (e.g. x86, x64, etc.)? I think there is some configuration missing in the test project to support anything other than x86.

**Comment by smorin4** [comment]
@mikebattista The tests are not running because the package references for MSTest.TestAdapter & MSTest.TestFramework are generated using version 2.2.8 instead of 2.2.10. Changing these to the latter fixes the problem.

As for the architecture support, you are correct that the test project only supports x86. Looking into solutions for this.

**Comment by mikebattista** [comment]
Remaining work:

- [ ] Test framework-dependent scenarios

**Comment by mikebattista** [comment]
Filed https://github.com/microsoft/TemplateStudio/issues/4576 to track main remaining issue.

**Review by mikebattista — APPROVED** [review]

**Pull request merged**
