### PR TITLE
Skip flaky tests (for now)

### PR DESCRIPTION
**Pull request by mrlacey**
# PR checklist

**Quick summary of changes**

This is the first part of the work for #4421 
It skips the tests that sometimes fail--without a clear indication why.

This is to increase the reliability of the tests that run as part of a PR.

**Which issue does this PR relate to?**

For #4421

**Applies to the following platforms:**

| UWP              | WPF              | WinUI            |
| :--------------- | :--------------- | :----------------|
| No | No | No |

**Anything that requires particular review or attention?**

no

**Do all automated tests pass?**

yes.
With the low-tech approach of running the test repeatedly and temporarily disabling any that fail until they repeatedly run without issue.

**Have automated tests been added for new features?**

n/a

**If you've changed the UI:**
  - Be sure you are including screenshots to show the changes.
  - Be sure you have reviewed the [accessibility checklist](accessibility.md).
 
n/a

**If you've included a new template:**
  - Be sure you reviewed the [Template Verification Checklist](https://github.com/microsoft/WindowsTemplateStudio/wiki/Checklist:-Template-Verification).
  - Be sure it's included in the list on this [UWP](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/getting-started-endusers.md) or [WPF](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/WPF/getting-started-endusers.md) getting started doc.

n/a

**Have you raised issues for any needed follow-on work?**

ongoing

**Have docs been updated?**

n/a

**If breaking changes or different ways of doing things have been introduced, have they been communicated widely?**

n/a

### CODE REVIEW

**Review by mikebattista — APPROVED** [review]

**Comment by mrlacey** [comment]
Still investigating the "couldn't find the file" issue

**Comment by mrlacey** [comment]
I've now worked out how to tell which file can't be found. Working on a fix now.

**Comment by mrlacey** [comment]
> I've now worked out how to tell which file can't be found. Working on a fix now.

Nope. It's not what I thought it was. Investigation continues.

**Comment by mrlacey** [comment]
I think I've now found, resolved, & tested the cause of some tests failing on the build server.
Visual Studio, Windows PowerShell, and PowerShell Core were each handling (or suppressing) exceptions differently which made it extremely challenging to diagnose and debug. :(

**Comment by mrlacey** [comment]
image

It's a pleasant change to see this 😃

**Comment by mikebattista** [comment]
Everything passed. Nice work.

**Pull request merged**
