### PR TITLE
Work-around for deploy not enabled in new WinUI projects

### PR DESCRIPTION
**Pull request by mrlacey**
# PR checklist

**Quick summary of changes**

Work-around for deployment issue of newly generated WinUI3 projects.
But a full fix for this when using VSEmulator.

**Which issue does this PR relate to?**

#4442

**Applies to the following platforms:**

- [x] WinUI
- [x] WPF
- [x] UWP

NOTE. This is a change made for WinUI projects but affects everything as it's in shared logic.

**Anything that requires particular review or attention?**

This is just a (hopefully) temporary work-around for the problem. 
More investigation is needed to identify the true cause of the issue.

The delay of three seconds is my best guess of how long to wait. 
Because I don't know exactly the cause of the issue, I don't know how long it is necessary to wait, it may also be connected to the machine that VS is running on and so want to allow sufficient time for machines under greater resource constraint than I've tested on.

The question that really needs to be asked is: Is a six-second delay in project generation better than relying on a person manually changing the generated project configuration? (And knowing that they have to!?)

**Do all automated tests pass?**

Yes.

**Have automated tests been added for new features?**

n/a

**If you've changed the UI:**
  - Be sure you are including screenshots to show the changes.
  - Be sure you have reviewed the [accessibility checklist](accessibility.md).

n/a

**If you've included a new template:**
  - Be sure you reviewed the [Template Verification Checklist](https://github.com/microsoft/TemplateStudio/wiki/Checklist:-Template-Verification).
  - Be sure it's included in the list on this [UWP](https://github.com/microsoft/TemplateStudio/blob/main/docs/UWP/getting-started-endusers.md) or [WPF](https://github.com/microsoft/TemplateStudio/blob/main/docs/WPF/getting-started-endusers.md) getting started doc.

n/a

**Have you raised issues for any needed follow-on work?**

Suggest leaving the original issue open to continue looking into this.

**Have docs been updated?**

n/a

**If breaking changes or different ways of doing things have been introduced, have they been communicated widely?**

n/a

### CODE REVIEW

**Comment by mrlacey** [comment]
@mikebattista assigning to you for review as this is related to something I think you'll want in the next release--which I assume you want to be soon based on the recent 1.1.2 release of WinAppSDK.

**Comment by mikebattista** [comment]
I will take a look. Thanks. Would be nice to include the next release.

**Comment by mikebattista** [comment]
@mrlacey was 3s arbitrarily chosen for the delay or did you test and discover that 3 seconds was the minimum to be reliable enough?

**Comment by mrlacey** [comment]
> @mrlacey was 3s arbitrarily chosen for the delay or did you test and discover that 3 seconds was the minimum to be reliable enough?

As per above, 3 seconds is a best guess. 1 second wasn't always enough and I don't know how much device capabilities (processor speed, other load, etc.) play a factor. I only tested on two fairly high spec machines but know they are above what a lot of developers use.

> Also in the description you said 6 second delay, is that because this is applied to both the App and Core projects?

Yes, six seconds because it's a delay per project and the default is to have 2 projects in the generated solution. For generations adding lots of other projects (e.g. a web backend or test projects) but these are not widely included. 
We can revisit if this is a problem but I doubt it will be

**Comment by mikebattista** [comment]
Given that this doesn't repro 100% and that the error dialog presented provides the fix when it does repro, I'm inclined not to take this workaround. The 6-9 second delay with 2-3 projects is a bit much and all extensions and projects would need to pay that penalty even though this problem only exists for the WinUI extension.

**Pull request closed without merging**
